# Generated by Django 5.1.3 on 2024-11-08 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ButtonClick',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('button_type', models.CharField(choices=[('location', 'Location'), ('contact', 'Contact')], max_length=10)),
                ('date_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
