# Generated by Django 5.1.3 on 2024-11-15 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='buttonclick',
            options={'ordering': ['custom_id']},
        ),
        migrations.AddField(
            model_name='buttonclick',
            name='custom_id',
            field=models.PositiveIntegerField(default=0, editable=False, unique=True),
        ),
    ]
